/* ============================================================
   contrapaul / make — /projects data
   Add a project by appending an entry to PROJECTS (any order —
   the timeline sorts itself and extends to cover new dates).

   Each entry:
     title:       string  (required)
     date:        "YYYY-MM" (required — month the project landed)
     cover:       image path (optional — striped slot shows if missing)
     images:      array of extra image paths (optional — delete freely)
     description: string (required)
     links:       array of { label, url } (optional — delete freely)
   ============================================================ */

const PROJECTS = [
  {
    title: "Project Title One",
    date: "2026-08",
    cover: "../images/projects/project-one.jpg",
    images: [
      "../images/projects/project-one-2.jpg",
      "../images/projects/project-one-3.jpg",
    ],
    description: "Placeholder description for the most recent project. A couple of sentences about what it is, why it exists, and what was learned building it.",
    links: [
      { label: "Write-up", url: "#" },
      { label: "Files", url: "#" },
    ],
  },
  {
    title: "Project Title Two",
    date: "2023-04",
    cover: "../images/projects/project-two.jpg",
    description: "A placeholder project with no extra images and no links — the minimum viable entry: title, date, cover, description.",
  },
  {
    title: "Project Title Three",
    date: "2024-01",
    cover: "../images/projects/project-three.jpg",
    images: ["../images/projects/project-three-2.jpg"],
    description: "Placeholder sitting before a two-month gap, so you can see how empty months keep the timeline evenly spaced.",
    links: [{ label: "GitHub", url: "#" }],
  },
  {
    title: "Project Title Four",
    date: "2024-02",
    cover: "../images/projects/project-four.jpg",
    description: "First of four projects in the same month — demonstrating the busiest layout the timeline supports.",
    links: [{ label: "Demo", url: "#" }],
  },
  {
    title: "Project Title Five",
    date: "2024-04",
    cover: "../images/projects/project-five.jpg",
    description: "Second of four projects in one month. On desktop these pair up side by side; on mobile they stack.",
  },
  {
    title: "Project Title Six",
    date: "2025-11",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2026-02",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2026-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2026-04",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2026-05",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2026-06",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2026-07",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2014-03",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2011-11",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2012-01",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2013-05",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2015-06",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2014-02",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2015-10",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2015-12",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2023-05",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2016-02",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2017-04",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2018-09",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2019-06",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2013-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2016-07",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2017-02",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2022-03",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2026-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2026-01",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2025-11",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2025-08",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2025-04",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2025-01",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2024-10",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2024-08",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2024-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2023-11",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2023-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2022-09",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2022-02",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2021-10",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2021-03",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2020-10",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2020-04",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2019-08",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2019-02",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2018-11",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2018-05",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2018-01",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2017-11",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2017-05",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2016-12",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2016-07",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2016-01",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2025-11",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2015-11",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Project Title Seven",
    date: "2015-01",
    cover: "../images/projects/project-seven.jpg",
    description: "Fourth of four projects in one month — the desktop cap. Anything past this stacks below.",
  },
  {
    title: "Project Title Six",
    date: "2014-06",
    cover: "../images/projects/project-six.jpg",
    images: ["../images/projects/project-six-2.jpg"],
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
  {
    title: "Spring Collection: 2014",
    date: "2014-04",
    cover: "../images/projects/spring2014.png",
    images: ["../images/projects/doppkits.jpg"]
    description: "My first 'capsule collection', consisting of backpacks, keychains, dopp kits, and tote bags. Also the last 'collection' under the 'contrapaul' name, as I'd rebrand in September 2014.",
  },
    {
    title: "Festival Packs Collaboration",
    date: "2014-02",
    cover: "../images/projects/billionaires.jpg",
    images: ["../images/projects/billion2.jpg"]
    description: "A friend of mine operated Billionaires Apparel, an 'underground' clothing brand and commissioned 9 backpacks after I produced a sample as a gift. 3 were black/purple, 3 black/neon blue, and 3 black/lime green.",
  },
   {
    title: "Accessory Bags",
    date: "2013-11",
    cover: "../images/projects/nov2013.jpg",
    description: "Third of four projects in one month, with one extra image and one link.",
    links: [{ label: "Write-up", url: "#" }],
  },
];
